#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format (will be overwritten by GitVersion)
version: 1.0.{build}-{branch}

# VM-Image
image: Visual Studio 2017 

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  OCTO_URL: https://cd.acceleratex.org/octopus
  OCTO_API_KEY:
    secure: n3HRVSbzxROMGgFXlO+aFwWPz/pXDQxh2l23x96en7E= # Encrypted variable: Go to "Encrypt data" page in account menu to encrypt data.
  COVERALLS_REPO_TOKEN:
    secure: tfcrsENk0VVns04RPBjJTqqPsTtiJzXG3aVq1QE4ltw3sd/UmHVYDAIuMraVwbxQ
  SL_USERNAME: ax_team
  SL_API_KEY:
    secure: VLNNEt3qzDJ+8bQegF4tXbCJL31rU0QZWBZTO8+sL8u2TyfZxJkN5RW1oeKHAqji  

# Only build non-tagged commits
skip_tags: true

# build cache to preserve files/folders between builds
cache:
    # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
    -  .\Sources\packages -> .\Sources\TimeTable\MyStik.TimeTable.Web\packages.config, .\Sources\TimeTable\MyStik.TimeTable.Data\packages.config, .\Sources\TimeTable\MyStik.TimeTable.DataServices\packages.config, .\Sources\TimeTable\MyStik.TimeTable.Contracts\packages.config, .\Sources\TimeTable\MyStik.TimeTable.Test\packages.config, .\Sources\TimeTable\MyStick.TimeTable.UaTest\packages.config
    -  .\tools -> .\tools\packages.config, .\setup.cake  # preserve "tools" directory in the root of build folder but will reset it if packages.config or setup.cake is modified

#---------------------------------#
#       build configuration       #
#---------------------------------#

# run custom scripts instead of automatic MSBuild
build_script:
    - ps: .\build.ps1 -target "Develop" -configuration "Release"

#---------------------------------#
#   general tests configuration   #
#---------------------------------#

# disable automatic tests
test: off    

#---------------------------------#
#     override common settings    #
#        branches to build        #
#---------------------------------#
# See: https://www.appveyor.com/blog/2017/08/01/sharing-configuration-between-branches-in-appveyor-yml/

for:
-
  branches:
    only:
      - /features?[/-]/
    
  build_script:
    - ps: .\build.ps1 -target "Develop" -configuration "Release"

  skip_tags: true    

-
  branches:
    only:
      - /releases?[/-]/
      - /dev(elop)?(ment)?$/
    
  build_script:
    - ps: .\build.ps1 -target "Integrate" -configuration "Release"   

  skip_tags: true  

-
  branches:
    only:
      - /hotfix(es)?[/-]/
      - /support?[/-]/
  
  build_script:
    - ps: .\build.ps1 -target "Integrate" -configuration "Release"

  skip_tags: false    

-
  branches:
    only:
      - master
  
  build_script:
    - ps: .\build.ps1 -target "Approval" -configuration "Release"    

  # Only build tagged commits like releases
  skip_non_tags: false

  skip_tags: false

# Fallback: Other branches, which are not specified above
-
  branches:
    only:
      - /.*/

  build_script:
    - ps: .\build.ps1 -target "Develop" -configuration "Debug"   

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: HipChat
    auth_token:
      secure: Ho4egHslrWIoatRGSw67km4gjib97dJDsnLYbBzpgjOrcEi+nINePrwSHi7X0Mpp
    room: NINE - RPS
  - provider: GitHubPullRequest
    auth_token:
      secure: BH3GjE8/qC3qqVcntcerjQHRbrP5DxniaxtVuowtn+x2ULSypOEsYUVlFKmZrfmZ
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
