// <auto-generated />
namespace MyStik.TimeTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OccurrenceGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OccurrenceGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201501101644232_OccurrenceGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
