// <auto-generated />
namespace MyStik.TimeTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InternshipV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InternshipV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071027041_InternshipV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
