// <auto-generated />
namespace MyStik.TimeTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ScriptShop_v01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScriptShop_v01));
        
        string IMigrationMetadata.Id
        {
            get { return "202107281605256_ScriptShop_v01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
