// <auto-generated />
namespace MyStik.TimeTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LotteryV10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LotteryV10));
        
        string IMigrationMetadata.Id
        {
            get { return "202402140727276_LotteryV10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
