// <auto-generated />
namespace MyStik.TimeTable.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    /// <summary>
    /// 
    /// </summary>
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserDevices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDevices));
        
        string IMigrationMetadata.Id
        {
            get { return "201511180653066_UserDevices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
