// <auto-generated />
namespace MyStik.TimeTable.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AlumniTEST : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlumniTEST));
        
        string IMigrationMetadata.Id
        {
            get { return "201504141726292_AlumniTEST"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
