// <auto-generated />
namespace MyStik.Gym.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class QuizSetsV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizSetsV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202305190654572_QuizSetsV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
