// <auto-generated />
namespace MyStik.Gym.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AccreditationV01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccreditationV01));
        
        string IMigrationMetadata.Id
        {
            get { return "202412011109492_AccreditationV01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
