//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStik.TimeTable.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyStik.TimeTable.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccreditationsString {
            get {
                return ResourceManager.GetString("AccreditationsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddressCantine {
            get {
                return ResourceManager.GetString("AddressCantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddressString {
            get {
                return ResourceManager.GetString("AddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AllCurriculas {
            get {
                return ResourceManager.GetString("AllCurriculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AllEventsString {
            get {
                return ResourceManager.GetString("AllEventsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AllModules {
            get {
                return ResourceManager.GetString("AllModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvailableLoginServices {
            get {
                return ResourceManager.GetString("AvailableLoginServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessHoursString {
            get {
                return ResourceManager.GetString("BusinessHoursString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessHoursTimeFriday {
            get {
                return ResourceManager.GetString("BusinessHoursTimeFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BusinessHoursTimeMondaytoThursday {
            get {
                return ResourceManager.GetString("BusinessHoursTimeMondaytoThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_431_-en.html#heute.
        /// </summary>
        public static string CantineHyperlink {
            get {
                return ResourceManager.GetString("CantineHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CantineMenuString {
            get {
                return ResourceManager.GetString("CantineMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CantineNoMenuAvailable {
            get {
                return ResourceManager.GetString("CantineNoMenuAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeEMailButton {
            get {
                return ResourceManager.GetString("ChangeEMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CommunicationSettingsHeading {
            get {
                return ResourceManager.GetString("CommunicationSettingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactHeading {
            get {
                return ResourceManager.GetString("ContactHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactLink {
            get {
                return ResourceManager.GetString("ContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactMailBody {
            get {
                return ResourceManager.GetString("ContactMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactMailSubject {
            get {
                return ResourceManager.GetString("ContactMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CoursePlanPanelHeading {
            get {
                return ResourceManager.GetString("CoursePlanPanelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreateCoursePlanButton {
            get {
                return ResourceManager.GetString("CreateCoursePlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CriteriaString {
            get {
                return ResourceManager.GetString("CriteriaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CurriculumField {
            get {
                return ResourceManager.GetString("CurriculumField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CurriculumNGroupEmptyMessage {
            get {
                return ResourceManager.GetString("CurriculumNGroupEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DashboardStudentHeading {
            get {
                return ResourceManager.GetString("DashboardStudentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeleteAccountButton {
            get {
                return ResourceManager.GetString("DeleteAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ECTSString {
            get {
                return ResourceManager.GetString("ECTSString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmployeesString {
            get {
                return ResourceManager.GetString("EmployeesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FacultyField {
            get {
                return ResourceManager.GetString("FacultyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.wi.hm.edu/en/index.en.html.
        /// </summary>
        public static string FacultyWebsiteHyperlink {
            get {
                return ResourceManager.GetString("FacultyWebsiteHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FacultyWebsiteShortDescriptionLink {
            get {
                return ResourceManager.GetString("FacultyWebsiteShortDescriptionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FeedString {
            get {
                return ResourceManager.GetString("FeedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileString {
            get {
                return ResourceManager.GetString("FileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPasswordHeading {
            get {
                return ResourceManager.GetString("ForgotPasswordHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPasswordSubmitButton {
            get {
                return ResourceManager.GetString("ForgotPasswordSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeFromString {
            get {
                return ResourceManager.GetString("FreeFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeRoomsForString {
            get {
                return ResourceManager.GetString("FreeRoomsForString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeRoomsHeading {
            get {
                return ResourceManager.GetString("FreeRoomsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeRoomsNow {
            get {
                return ResourceManager.GetString("FreeRoomsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeRoomsSoonString {
            get {
                return ResourceManager.GetString("FreeRoomsSoonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeString {
            get {
                return ResourceManager.GetString("FreeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeUntilEveningString {
            get {
                return ResourceManager.GetString("FreeUntilEveningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeUntilString {
            get {
                return ResourceManager.GetString("FreeUntilString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FridayString {
            get {
                return ResourceManager.GetString("FridayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GlobalCatalogString {
            get {
                return ResourceManager.GetString("GlobalCatalogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GroupsString {
            get {
                return ResourceManager.GetString("GroupsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GuestsString {
            get {
                return ResourceManager.GetString("GuestsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMJobonautDescription {
            get {
                return ResourceManager.GetString("HMJobonautDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HMJobonautDescription2 {
            get {
                return ResourceManager.GetString("HMJobonautDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string iCalFeedExplanation {
            get {
                return ResourceManager.GetString("iCalFeedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string iCalFeedURL {
            get {
                return ResourceManager.GetString("iCalFeedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string iCalFileDownload {
            get {
                return ResourceManager.GetString("iCalFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string iCalString {
            get {
                return ResourceManager.GetString("iCalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImprintHeading {
            get {
                return ResourceManager.GetString("ImprintHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hm.edu/en/secondarynavigation/impressum_1/legal_notice_1.en.html.
        /// </summary>
        public static string ImprintHyperlink {
            get {
                return ResourceManager.GetString("ImprintHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImprintLink {
            get {
                return ResourceManager.GetString("ImprintLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InactiveNoContactInf {
            get {
                return ResourceManager.GetString("InactiveNoContactInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InactiveUseEmail {
            get {
                return ResourceManager.GetString("InactiveUseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsReserved {
            get {
                return ResourceManager.GetString("IsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JobsNewsletterFK09Description {
            get {
                return ResourceManager.GetString("JobsNewsletterFK09Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JobsNewsletterFK09Description2 {
            get {
                return ResourceManager.GetString("JobsNewsletterFK09Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JobsPanelHeading {
            get {
                return ResourceManager.GetString("JobsPanelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JobsString {
            get {
                return ResourceManager.GetString("JobsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string KeyString {
            get {
                return ResourceManager.GetString("KeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LectureSchedulerHeading {
            get {
                return ResourceManager.GetString("LectureSchedulerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LecturesHeading {
            get {
                return ResourceManager.GetString("LecturesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LinkString {
            get {
                return ResourceManager.GetString("LinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LocalUserAccountHeading {
            get {
                return ResourceManager.GetString("LocalUserAccountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginAppLinksHeading {
            get {
                return ResourceManager.GetString("LoginAppLinksHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginHeading {
            get {
                return ResourceManager.GetString("LoginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginProviderHeading {
            get {
                return ResourceManager.GetString("LoginProviderHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoginTab {
            get {
                return ResourceManager.GetString("LoginTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LVsString {
            get {
                return ResourceManager.GetString("LVsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ManageLoginsLink {
            get {
                return ResourceManager.GetString("ManageLoginsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ManageProfileHeading {
            get {
                return ResourceManager.GetString("ManageProfileHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ManageProfileHeading2 {
            get {
                return ResourceManager.GetString("ManageProfileHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MealString {
            get {
                return ResourceManager.GetString("MealString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MeatLoafBreadString {
            get {
                return ResourceManager.GetString("MeatLoafBreadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuCantine {
            get {
                return ResourceManager.GetString("MenuCantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuCurrent {
            get {
                return ResourceManager.GetString("MenuCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuPersons {
            get {
                return ResourceManager.GetString("MenuPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuRooms {
            get {
                return ResourceManager.GetString("MenuRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuStudies {
            get {
                return ResourceManager.GetString("MenuStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModuleCatalogString {
            get {
                return ResourceManager.GetString("ModuleCatalogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModulesString {
            get {
                return ResourceManager.GetString("ModulesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MondayToThursdayString {
            get {
                return ResourceManager.GetString("MondayToThursdayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MVString {
            get {
                return ResourceManager.GetString("MVString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyCoursePlan {
            get {
                return ResourceManager.GetString("MyCoursePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyCoursePlanHeading {
            get {
                return ResourceManager.GetString("MyCoursePlanHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyPersonalData {
            get {
                return ResourceManager.GetString("MyPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MySettings {
            get {
                return ResourceManager.GetString("MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyStudyBook {
            get {
                return ResourceManager.GetString("MyStudyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyTimeTableHeading {
            get {
                return ResourceManager.GetString("MyTimeTableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyUserProfile {
            get {
                return ResourceManager.GetString("MyUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsletterHeading {
            get {
                return ResourceManager.GetString("NewsletterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NextDate {
            get {
                return ResourceManager.GetString("NextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NextLink {
            get {
                return ResourceManager.GetString("NextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NextOccupancyString {
            get {
                return ResourceManager.GetString("NextOccupancyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoDates {
            get {
                return ResourceManager.GetString("NoDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoDeviceRegisteredMessage {
            get {
                return ResourceManager.GetString("NoDeviceRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoGroup {
            get {
                return ResourceManager.GetString("NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NowLink {
            get {
                return ResourceManager.GetString("NowLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumberSeatsString {
            get {
                return ResourceManager.GetString("NumberSeatsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumberString {
            get {
                return ResourceManager.GetString("NumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OccupiedByString {
            get {
                return ResourceManager.GetString("OccupiedByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeHour {
            get {
                return ResourceManager.GetString("OfficeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeHourByAgreement {
            get {
                return ResourceManager.GetString("OfficeHourByAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeHourWithDates {
            get {
                return ResourceManager.GetString("OfficeHourWithDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganicString {
            get {
                return ResourceManager.GetString("OrganicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizerString {
            get {
                return ResourceManager.GetString("OrganizerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersonalDataHeading {
            get {
                return ResourceManager.GetString("PersonalDataHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PlanButton {
            get {
                return ResourceManager.GetString("PlanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PreviewString {
            get {
                return ResourceManager.GetString("PreviewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PricesforString {
            get {
                return ResourceManager.GetString("PricesforString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PriceString {
            get {
                return ResourceManager.GetString("PriceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivacyLink {
            get {
                return ResourceManager.GetString("PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProfileListActiveLecturer {
            get {
                return ResourceManager.GetString("ProfileListActiveLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QuickAccessFreeRooms {
            get {
                return ResourceManager.GetString("QuickAccessFreeRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QuickAccessHeading {
            get {
                return ResourceManager.GetString("QuickAccessHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QuickAccessOfficeHour {
            get {
                return ResourceManager.GetString("QuickAccessOfficeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QuickAccessTimeTablePlaner {
            get {
                return ResourceManager.GetString("QuickAccessTimeTablePlaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterEmailField {
            get {
                return ResourceManager.GetString("RegisterEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterEmailPlaceholder {
            get {
                return ResourceManager.GetString("RegisterEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterFirstNameField {
            get {
                return ResourceManager.GetString("RegisterFirstNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterFirstNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterFirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterHeading {
            get {
                return ResourceManager.GetString("RegisterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterLastNameField {
            get {
                return ResourceManager.GetString("RegisterLastNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterLastNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterLastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPasswordAgainPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPasswordAgainPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPasswordConfirmErrorMessage {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPasswordConfirmField {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirmField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPasswordLengthErrorMessage {
            get {
                return ResourceManager.GetString("RegisterPasswordLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterPrivacyField {
            get {
                return ResourceManager.GetString("RegisterPrivacyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterSubmitButton {
            get {
                return ResourceManager.GetString("RegisterSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterTabHeading {
            get {
                return ResourceManager.GetString("RegisterTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RegisterValidationSummaryMessage {
            get {
                return ResourceManager.GetString("RegisterValidationSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoomNumberString {
            get {
                return ResourceManager.GetString("RoomNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoomOwnerString {
            get {
                return ResourceManager.GetString("RoomOwnerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoomsHeading {
            get {
                return ResourceManager.GetString("RoomsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RoomStatusString {
            get {
                return ResourceManager.GetString("RoomStatusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SchnitzelBreadString {
            get {
                return ResourceManager.GetString("SchnitzelBreadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SemesterString {
            get {
                return ResourceManager.GetString("SemesterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SemGroupField {
            get {
                return ResourceManager.GetString("SemGroupField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SetMailingSettingCheckbox {
            get {
                return ResourceManager.GetString("SetMailingSettingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SetPasswordButton {
            get {
                return ResourceManager.GetString("SetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsString {
            get {
                return ResourceManager.GetString("SettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShortNameString {
            get {
                return ResourceManager.GetString("ShortNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShowAsLabel {
            get {
                return ResourceManager.GetString("ShowAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShowSubscribedDates {
            get {
                return ResourceManager.GetString("ShowSubscribedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SnacksString {
            get {
                return ResourceManager.GetString("SnacksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SnacksTableContent {
            get {
                return ResourceManager.GetString("SnacksTableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SoftDrinksString {
            get {
                return ResourceManager.GetString("SoftDrinksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StuCafeEmptyMessage {
            get {
                return ResourceManager.GetString("StuCafeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StuCafeHeading {
            get {
                return ResourceManager.GetString("StuCafeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyBook {
            get {
                return ResourceManager.GetString("StudyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyBookSemProfileSubscriptionsHeading {
            get {
                return ResourceManager.GetString("StudyBookSemProfileSubscriptionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyProcessComment {
            get {
                return ResourceManager.GetString("StudyProcessComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyProcessHeading {
            get {
                return ResourceManager.GetString("StudyProcessHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuAlumni {
            get {
                return ResourceManager.GetString("SubMenuAlumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuCantine {
            get {
                return ResourceManager.GetString("SubMenuCantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuCurrentEvents {
            get {
                return ResourceManager.GetString("SubMenuCurrentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuCurrentJobs {
            get {
                return ResourceManager.GetString("SubMenuCurrentJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuCurrentNewsletter {
            get {
                return ResourceManager.GetString("SubMenuCurrentNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuLecturer {
            get {
                return ResourceManager.GetString("SubMenuLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuRoomsFreeRooms {
            get {
                return ResourceManager.GetString("SubMenuRoomsFreeRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuRoomsOccupancy {
            get {
                return ResourceManager.GetString("SubMenuRoomsOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudents {
            get {
                return ResourceManager.GetString("SubMenuStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudiesCurricula {
            get {
                return ResourceManager.GetString("SubMenuStudiesCurricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudiesModules {
            get {
                return ResourceManager.GetString("SubMenuStudiesModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudiesPlaner {
            get {
                return ResourceManager.GetString("SubMenuStudiesPlaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudiesSemester {
            get {
                return ResourceManager.GetString("SubMenuStudiesSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubMenuStudiesThesis {
            get {
                return ResourceManager.GetString("SubMenuStudiesThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Subscriber {
            get {
                return ResourceManager.GetString("Subscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubscribersString {
            get {
                return ResourceManager.GetString("SubscribersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TodayString {
            get {
                return ResourceManager.GetString("TodayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.hm.edu/en/index.en.html.
        /// </summary>
        public static string UniversityWebsiteHyperlink {
            get {
                return ResourceManager.GetString("UniversityWebsiteHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UniversityWebsiteShortDescriptionLink {
            get {
                return ResourceManager.GetString("UniversityWebsiteShortDescriptionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserDevicesControlHeading {
            get {
                return ResourceManager.GetString("UserDevicesControlHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VeganString {
            get {
                return ResourceManager.GetString("VeganString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VegetarianString {
            get {
                return ResourceManager.GetString("VegetarianString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VisibleForString {
            get {
                return ResourceManager.GetString("VisibleForString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WaitingList {
            get {
                return ResourceManager.GetString("WaitingList", resourceCulture);
            }
        }
    }
}
